title: Lennard Henze
author:
  name: Lennard Henze
  email: lennard.henze@gmx.de
description: >
  My personal side. I post thoughts on technical stuff here.
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
minima:
  skin: auto
